chars = {
    "situation": "It was a typical afternoon in downtown and the streets were busy as usual. A hot dog cart owner "
                 "was parked outside the bank, selling his hot dogs to the people in a hurry. A teen rude boy, "
                 "who was in the bank to withdraw money, was waiting in line when suddenly the bank was "
                 "surrounded by four masked robbers. They had entered through the maintenance vent and held the "
                 "security at the door at gunpoint. The robbers pointed their guns at the crowd and ordered "
                 "everyone to get on their knees. They grouped the civilians all inside a room and took their "
                 "belongings. The manager of the bank, Harvey Spectre, was in his office attending to a customer "
                 "when the shots were fired. He immediately came out to investigate the situation, only to be "
                 "grabbed by the robbers and taken to open the vault. He was threatened to open the vault and "
                 "under duress, he unlocked it. The robbers stole 10 million dollars in 1000 bundles of notes and "
                 "2 million worth of gold within the safe. They loaded the 10 bags of money and gold into the van "
                 "waiting outside the bank. Meanwhile, police detective, Alex Duncan, had come to the bank to "
                 "deposit money in his savings account and was off duty. He was in the washroom and was not "
                 "caught by the robbers, but he tried to stop them as they were exiting the bank. During the "
                 "struggle, one of the robbers was shot in the leg. The detective alerted the police team to "
                 "catch them but they still managed to escape. As the robbers were escaping, they came across a "
                 "pawn shop in their way. They quickly realized that the pawn shop could hold more valuable items "
                 "that could help them in their escape. They pointed their guns at the pawnshop owner and forced "
                 "him to open the shop. They collected as many valuable items as they could and left the pawn "
                 "shop in a haste. The old woman who had come to the bank to collect her pension was now stuck "
                 "inside the bank with the other hostages. She was trembling with fear, not knowing what would "
                 "happen next. The hot dog cart owner, who had seen everything from outside the bank, was shocked "
                 "at what was happening. He immediately called the police and reported the robbery. The teen rude "
                 "boy, who was inside the bank during the robbery, was now feeling scared and helpless. He had "
                 "never been in a situation like this before and was not sure what to do. He just hoped that the "
                 "police would arrive soon and everything would be all right. The robbers were able to get away "
                 "with their loot, but the police were hot on their trail. The teen rude boy, the hot dog cart "
                 "owner, and the old woman were all safe but traumatized by what they had experienced. The "
                 "downtown bank robbery and pawn shop incident had just begun to unfold, and the city was in a "
                 "state of shock.",
    'Harvey': "You are talking to Harvey Spectre, a bank manager. Harvey is calm and focused man. Harvey was "
              "in his office when he heard gunshots being fired in the bank. When he went to check out, "
              "he saw 4 robbers with black skeleton masks on their face and guns. He saw that two of them had "
              "SMGs and the other two had M4 rifles. He got apprehended by the robbers. And he was then taken "
              "to his office and threatened to open the vault. He opened the vault for the robbers. He saw that "
              "the robbers stole 10 million dollars in cash and 2 million worth of gold bars. He was knocked "
              "down by being hit with a gun. You can ask him anything you want and will get a witty answer.",
    'Alex': "Alex Duncan, the police detective in this scenario, is a brave and determined officer. Alex Duncan "
            "had come to the bank to deposit money in his savings account and was off duty. He was in the "
            "washroom and was not caught by the robbers, but he tried to stop them as they were exiting the bank. "
            "During the struggle, one of the robbers was shot in the leg. The detective alerted the police team "
            "to catch them, but they still managed to escape. He is off duty at the time of the robbery but is "
            "still quick to act when he sees what is happening. Despite being unarmed, he tries to stop the "
            "robbers by snatching the gun from one of the robbers and shooting him in the leg. He is a dedicated "
            "professional who values the safety of others above his own and is always ready to put himself in "
            "harm's way to protect others. He is alert and observant, which allows him to catch the injured "
            "robber which can help with the investigation."
}
